[package]
name = "fearless_nes"
version = "0.1.0"
authors = ["TomasKralCZ <tomas@kral.hk>"]
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.1"
siphasher = "0.3"
roxmltree = "0.15"
sha-1 = "0.10"
thiserror = "1.0"

[features]
integration_tests = []

[[bin]]
name = "bench"
